spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sprinboot_jpa
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: password
    baseline-description: "init"
    baseline-version: 0
    locations: classpath:db/migration
